version: "3.8"

services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    restart: unless-stopped
    ports:
      - "8042:8042" # HTTP API / Web UI
      - "4242:4242" # DICOM
    environment:
      VERBOSE_STARTUP: "true"
      ORTHANC__NAME: "orthanc-local"
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
    volumes:
      - orthanc-storage:/var/lib/orthanc/db

volumes:
  orthanc-storage:
